title: Mr. Marshmello
email: brentyi@berkeley.edu
description: > # this means to ignore newlines until "baseurl:"
  An assistive eating robot
highlighter: rouge

collections:
  sections:
    output: false

defaults:
  -
    scope:
      path: ""
    values:
      latex: no
lsi: false
safe: true
source: autoM
incremental: false
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# theme: minima
plugins:
  - octopress-autoprefixer
exclude:
  - Gemfile
  - Gemfile.lock
